# Generated by Django 3.2.4 on 2021-06-26 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
