# Generated by Django 3.2.4 on 2021-06-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogs_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
