# Generated by Django 3.2.4 on 2021-06-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_blogs_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='img',
        ),
    ]
